apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prod
data:
  DJANGO_ALLOWED_HOSTS: "0.0.0.0,127.0.0.1,localhost,users-api-svc,users-api-svc.prod.svc.cluster.local"
  DJANGO_DEBUG: "True"
  DB_HOST: "<TU_RDS_ENDPOINT>"
  DB_NAME: "registrodb"
  DB_PORT: "5432"
  DB_SSLMODE: "require"
  NOTIFY_URL: "http://notification-service:5000/notify"
