apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
  namespace: app
type: Opaque
stringData:
  DB_HOST: users-db.c5hfr4xyppqi.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASS: UsersDb2025!
