apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: prod
type: Opaque
stringData:
  DB_NAME: "registrodb"
  DB_USER: "postgres"
  DB_PASS: "1234"                         # <-- tu password
  DB_HOST: "pg-postgresql.prod.svc.cluster.local"
  DB_PORT: "5432"
