# users-api/k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: users-secrets
  namespace: prod
type: Opaque
stringData:
  DB_HOST: "<rds-endpoint>"
  DB_PORT: "5432"
  DB_NAME: "registrodb"
  DB_USER: "postgres"
  DB_PASS: "<password>"
  SECRET_KEY: "<genera-uno-seguro>"