apiVersion: v1
kind: Service
metadata:
  name: users-api-nlb
  namespace: app
  labels:
    app: users-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "traffic-port"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "stickiness.enabled=false"
spec:
  type: LoadBalancer
  selector:
    app: users-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  externalTrafficPolicy: Cluster
